#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
h=0
while [ $h -le 12 ]
do
    m=1
    while [ $m -le 59 ]
    do
        echo "$h h: $m m"
        m=$((m + 1))
    done
    h=$((h + 1))
done
