#!/usr/bin/env bash
# Gives information about the school file
if [ -e "school" ]
then
    if [ -f "school" ]
    then
        echo "File exist and is a regular file"
        if [ -s "school" ]
        then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    else
        echo "school file exists"
    fi
else
    echo "school file does not exist"
fi
