#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely and print message when receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
